### ISSUE TITLE
Question: performance & shared msg specializations?

### ISSUE THREAD

**Issue by SebastianRiedel** [osrf/rosbag_direct_write#11]
1) Is / Can the full code for the specialized message definitions (e.g. Image, PointCloud) be made available?

2) From your experience, how much do you gain in throughput e.g. for PointCloud messages?

**Comment by wjwwood** [comment]
> Is / Can the full code for the specialized message definitions (e.g. Image, PointCloud) be made available?

I guess you mean the code that allows you to directly write to the file for specific message types? This is all that is out there public:

https://github.com/osrf/rosbag_direct_write#zero-copy-direct-writing

This was used on Project Tango, and that's the only place I am aware of where the code is in use, but that's not public AFAIK.

There is also this test code:

https://github.com/osrf/rosbag_direct_write/blob/master/test/direct_PointCloud2.h

> From your experience, how much do you gain in throughput e.g. for PointCloud messages?

Depends on your hardware. I saw a small improvement on desktop machines, but on other platforms you might see a large performance improvement, depending on the speed of your disk and memory. I don't have any hard numbers. I would say it is strictly better than using `rosbag record`, though I can't quantify by how much. So it may or may not be worth the effort of setting it up.

**Comment by wjwwood** [comment]
I'll close this for now, feel free to continue the discussion.
