### ISSUE TITLE
Question: state of this package

### ISSUE THREAD

**Issue by facontidavide** [osrf/rosbag_direct_write#7]
Hi,

I am testing this library and benchmarking it against the default robag_storage.

I wonder if the project is usable in production and why it was not merged with the default ros_comm repository as one of the possible backends of rosbag.

Is there any limitation or drawback I should be aware of before using it?

Davide

**Comment by wjwwood** [comment]
@facontidavide sorry, I wasn't watching the repo 😨.

We worked on this for a project with Google, and while it is finished and working, I never had the time to finish documenting it and release it.

Even more work would be to integrate it into `rosbag` in `ros_comm`. That would be great to do, but I just don't have the time.

There's no reason for you to avoid using it, but it doesn't have a CLI front end at all. You have to write code that subscribes and push that into the bag yourself.
